import { useState, useRef, useEffect, useCallback, useMemo } from 'react'
import {
  Send, Loader2, Sparkles, Plus, Trash2, Download, FileCode2, FileJson, Grid3X3,
  ZoomIn, ZoomOut, RotateCcw, Upload, Image as ImageIcon, X, ChevronDown, ChevronRight,
  Monitor, Tablet, Smartphone, MousePointer2, Move, Maximize2, Copy, Layers, Settings,
  Eye, EyeOff, Lock, Unlock, Wand2, ChevronUp, PanelLeft, PanelRight, Zap
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { supabaseUrl } from '@/config/supabase'

const CHAT_API = `${supabaseUrl}/functions/v1/rodin-api?action=ui-generate`

const ROBLOX_DEFAULTS: Record<string, any> = {
  BackgroundColor3: '#c8c8c8', BackgroundTransparency: 0, BorderSizePixel: 1,
  BorderColor3: '#000000', AnchorPoint: { X: 0, Y: 0 },
  Rotation: 0, ZIndex: 1, LayoutOrder: 0,
  TextColor3: '#000000', TextTransparency: 0, TextScaled: false,
  Font: 'Legacy', TextSize: 14, TextWrapped: false, TextXAlignment: 'Center',
  TextYAlignment: 'Center', RichText: false,
  Image: '', ImageColor3: '#ffffff', ImageTransparency: 0,
  ScrollBarThickness: 12, ScrollBarImageColor3: '#000000',
  CanvasSize: { X: 0, Y: 200 }, AutomaticCanvasSize: 'None',
  CornerRadius: 0, Padding: 0,
}

const DEVICES = [
  { name: 'Desktop', w: 1920, h: 1080, icon: Monitor },
  { name: 'Tablet', w: 1024, h: 768, icon: Tablet },
  { name: 'Mobile', w: 540, h: 960, icon: Smartphone },
]

const ELEMENT_TYPES = [
  { type: 'Frame', label: 'Frame', desc: 'Container' },
  { type: 'TextLabel', label: 'TextLabel', desc: 'Text' },
  { type: 'TextButton', label: 'TextButton', desc: 'Button' },
  { type: 'ImageLabel', label: 'ImageLabel', desc: 'Image' },
  { type: 'ScrollingFrame', label: 'ScrollFrame', desc: 'Scroll' },
  { type: 'TextBox', label: 'TextBox', desc: 'Input' },
]

const PROP_GROUPS: Record<string, string[]> = {
  'Data': ['Name', 'LayoutOrder', 'Visible'],
  'Appearance': ['BackgroundColor3', 'BackgroundTransparency', 'BorderColor3', 'BorderSizePixel', 'Image', 'ImageColor3', 'ImageTransparency'],
  'Text': ['Text', 'TextColor3', 'TextTransparency', 'TextScaled', 'Font', 'TextSize', 'TextWrapped', 'TextXAlignment', 'TextYAlignment', 'RichText'],
  'Layout': ['Position', 'Size', 'AnchorPoint', 'Rotation', 'ZIndex'],
  'Corner': ['CornerRadius'],
  'Scroll': ['ScrollBarThickness', 'ScrollBarImageColor3', 'CanvasSize', 'AutomaticCanvasSize'],
}

let _id = 0
const uid = () => `e${++_id}`

function parseColor(c: any): string {
  if (!c || c === '#000000' && false) return '#c8c8c8'
  if (typeof c === 'string' && c.startsWith('#')) return c
  if (typeof c === 'object' && c !== null && 'R' in c) {
    const r = Math.round((c.R || 0) * 255)
    const g = Math.round((c.G || 0) * 255)
    const b = Math.round((c.B || 0) * 255)
    return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`
  }
  return String(c)
}

function colorToRoblox(hex: string): string {
  const h = hex.replace('#', '')
  if (h.length !== 6) return 'Color3.new(0.78, 0.78, 0.78)'
  const r = (parseInt(h.slice(0, 2), 16) / 255).toFixed(2)
  const g = (parseInt(h.slice(2, 4), 16) / 255).toFixed(2)
  const b = (parseInt(h.slice(4, 6), 16) / 255).toFixed(2)
  return `Color3.new(${r}, ${g}, ${b})`
}

function getDefaultProp(key: string): any {
  return ROBLOX_DEFAULTS[key] ?? (typeof ROBLOX_DEFAULTS[key] === 'number' ? 0 : typeof ROBLOX_DEFAULTS[key] === 'boolean' ? false : '')
}

function differsFromDefault(key: string, value: any): boolean {
  const def = ROBLOX_DEFAULTS[key]
  if (def === undefined) return true
  if (typeof def === 'object' && typeof value === 'object') return JSON.stringify(def) !== JSON.stringify(value)
  return def !== value
}

export interface UIEl {
  id: string; type: string; name: string; parentId: string | null
  position: { X: number; Y: number }; size: { X: number; Y: number }
  props: Record<string, any>; children: string[]; zIndex: number; locked: boolean; visible: boolean
}

interface ChatMsg { role: 'user' | 'assistant'; content: string; commands?: any[] }

// ─── Lua Generator ───────────────────────────────────────────
function genVarName(el: UIEl, parent?: UIEl): string {
  const base = el.name.replace(/[^a-zA-Z0-9]/g, '')
  return base.charAt(0).toLowerCase() + base.slice(1)
}

function genLua(elements: UIEl[]): string {
  const lines: string[] = [
    '-- Generated by Yobest UI Builder',
    '-- Paste into Roblox Studio Command Bar or a LocalScript',
    '',
    'local screenGui = Instance.new("ScreenGui")',
    'screenGui.Name = "GeneratedUI"',
    'screenGui.ResetOnSpawn = false',
    'screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling',
    'screenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")',
    '',
  ]
  const map = new Map(elements.map(e => [e.id, e]))

  function emit(el: UIEl, parentVar: string, depth: number) {
    const v = genVarName(el)
    lines.push(`${'  '.repeat(depth)}local ${v} = Instance.new("${el.type}")`)
    lines.push(`${'  '.repeat(depth)}${v}.Name = "${el.name}"`)

    // Position & Size
    lines.push(`${'  '.repeat(depth)}${v}.Position = UDim2.new(${el.position.X}, 0, ${el.position.Y}, 0)`)
    lines.push(`${'  '.repeat(depth)}${v}.Size = UDim2.new(${el.size.X}, 0, ${el.size.Y}, 0)`)

    // Properties that differ from defaults
    for (const [k, val] of Object.entries(el.props)) {
      if (k === 'Position' || k === 'Size') continue
      if (!differsFromDefault(k, val)) continue
      if (val === undefined || val === null) continue

      if (k === 'BackgroundColor3' || k === 'TextColor3' || k === 'BorderColor3' || k === 'ImageColor3') {
        lines.push(`${'  '.repeat(depth)}${v}.${k} = ${colorToRoblox(parseColor(val))}`)
      } else if (k === 'CornerRadius') {
        lines.push(`${'  '.repeat(depth)}${v}.CornerRadius = UDim.new(0, ${val})`)
      } else if (k === 'AnchorPoint' && typeof val === 'object') {
        lines.push(`${'  '.repeat(depth)}${v}.AnchorPoint = Vector2.new(${val.X}, ${val.Y})`)
      } else if (k === 'CanvasSize' && typeof val === 'object') {
        lines.push(`${'  '.repeat(depth)}${v}.CanvasSize = UDim2.new(${val.X}, 0, ${val.Y}, 0)`)
      } else if (typeof val === 'string') {
        lines.push(`${'  '.repeat(depth)}${v}.${k} = "${val}"`)
      } else if (typeof val === 'boolean') {
        lines.push(`${'  '.repeat(depth)}${v}.${k} = ${val ? 'true' : 'false'}`)
      } else if (typeof val === 'number') {
        lines.push(`${'  '.repeat(depth)}${v}.${k} = ${val}`)
      }
    }
    lines.push(`${'  '.repeat(depth)}${v}.Parent = ${parentVar}`)
    lines.push('')

    for (const cid of el.children) {
      const child = map.get(cid)
      if (child && child.visible) emit(child, v, depth + 1)
    }
  }

  const roots = elements.filter(e => !e.parentId)
  for (const root of roots) emit(root, 'screenGui', 0)
  lines.push('')
  lines.push('print("UI Generated by Yobest UI Builder!")')
  return lines.join('\n')
}

function genJSON(elements: UIEl[]): string {
  return JSON.stringify(elements.map(e => ({
    type: e.type, name: e.name, parentId: e.parentId,
    position: e.position, size: e.size, props: e.props,
    children: e.children, zIndex: e.zIndex,
  })), null, 2)
}

function escapeXml(s: string) { return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }

function genRbxmx(elements: UIEl[]): string {
  const map = new Map(elements.map(e => [e.id, e]))
  let xml = '<?xml version="1.0" encoding="utf-8"?>\n<roblox version="4">\n'
  function emit(el: UIEl, ind = 1) {
    const p = '  '.repeat(ind)
    xml += `${p}<Item class="${el.type}">\n${p}  <Properties>\n${p}    <string name="Name">${escapeXml(el.name)}</string>\n`
    xml += `${p}    <UDim2 name="Position">{${el.position.X}, 0},{${el.position.Y}, 0}</UDim2>\n`
    xml += `${p}    <UDim2 name="Size">{${el.size.X}, 0},{${el.size.Y}, 0}</UDim2>\n`
    for (const [k, v] of Object.entries(el.props)) {
      if (['Position', 'Size', 'Name'].includes(k)) continue
      if (k === 'BackgroundColor3' || k === 'TextColor3' || k === 'BorderColor3' || k === 'ImageColor3') {
        const h = parseColor(v).replace('#', '')
        if (h.length === 6) xml += `${p}    <Color3 name="${k}">${parseInt(h.slice(0, 2), 16)}, ${parseInt(h.slice(2, 4), 16)}, ${parseInt(h.slice(4, 6), 16)}</Color3>\n`
      } else if (k === 'CornerRadius') {
        xml += `${p}    <UDim name="CornerRadius">{0, ${v}}</UDim>\n`
      } else if (k === 'AnchorPoint' && typeof v === 'object') {
        xml += `${p}    <Vector2 name="AnchorPoint">${v.X}, ${v.Y}</Vector2>\n`
      } else if (typeof v === 'string') {
        xml += `${p}    <string name="${k}">${escapeXml(v)}</string>\n`
      } else if (typeof v === 'number') {
        xml += `${p}    <float name="${k}">${v}</float>\n`
      } else if (typeof v === 'boolean') {
        xml += `${p}    <bool name="${k}">${v}</bool>\n`
      }
    }
    xml += `${p}  </Properties>\n`
    for (const cid of el.children) { const c = map.get(cid); if (c) emit(c, ind + 1) }
    xml += `${p}</Item>\n`
  }
  for (const root of elements.filter(e => !e.parentId)) emit(root)
  xml += '</roblox>'
  return xml
}

// ─── Main Component ──────────────────────────────────────────
export default function UIGenerator() {
  const [elements, setElements] = useState<UIEl[]>([])
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [buildMode, setBuildMode] = useState(true)
  const [device, setDevice] = useState(0)
  const [zoom, setZoom] = useState(0.55)
  const [pan, setPan] = useState({ x: 0, y: 0 })
  const [isPanning, setIsPanning] = useState(false)
  const [panStart, setPanStart] = useState({ x: 0, y: 0, px: 0, py: 0 })
  const [showGrid, setShowGrid] = useState(true)
  const [snapToGrid, setSnapToGrid] = useState(true)
  const gridSize = 20

  // Chat
  const [messages, setMessages] = useState<ChatMsg[]>([])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [showChat, setShowChat] = useState(true)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  // Panels
  const [showLayers, setShowLayers] = useState(true)
  const [showProps, setShowProps] = useState(true)
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(new Set(['Data', 'Appearance', 'Layout']))

  // Export
  const [showExport, setShowExport] = useState(false)
  const [showImageSearch, setShowImageSearch] = useState(false)
  const [imageUrl, setImageUrl] = useState('')
  const [instantBuild, setInstantBuild] = useState(() => localStorage.getItem('ui-instant-build') === 'true')

  // Drag & Resize
  const [dragging, setDragging] = useState(false)
  const [dragData, setDragData] = useState<{ sx: number; sy: number; ox: number; oy: number } | null>(null)
  const [resizing, setResizing] = useState(false)
  const [resizeData, setResizeData] = useState<{ sx: number; sy: number; ow: number; oh: number; corner: string } | null>(null)

  // History
  const [hist, setHist] = useState<UIEl[][]>([[]])
  const [histIdx, setHistIdx] = useState(0)

  const canvasRef = useRef<HTMLDivElement>(null)
  const selected = useMemo(() => elements.find(e => e.id === selectedId) || null, [elements, selectedId])

  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages])

  // Sync instant build to localStorage
  useEffect(() => { localStorage.setItem('ui-instant-build', String(instantBuild)) }, [instantBuild])

  // History helpers
  const pushHist = useCallback((els: UIEl[]) => {
    setHist(h => [...h.slice(0, histIdx + 1), els])
    setHistIdx(i => i + 1)
  }, [histIdx])
  const undo = useCallback(() => { if (histIdx > 0) { setHistIdx(histIdx - 1); setElements(hist[histIdx - 1]); setSelectedId(null) } }, [histIdx, hist])
  const redo = useCallback(() => { if (histIdx < hist.length - 1) { setHistIdx(histIdx + 1); setElements(hist[histIdx + 1]); setSelectedId(null) } }, [histIdx, hist])

  // Snap helper
  const snap = (v: number) => snapToGrid ? Math.round(v * 1000) / 1000 : v

  // ─── Element CRUD ───
  const addEl = useCallback((type: string, parentId?: string | null) => {
    const id = uid()
    const count = elements.filter(e => e.type === type).length + 1
    const el: UIEl = {
      id, type, name: `${type}${count}`, parentId: parentId ?? null,
      position: { X: 0.5, Y: 0.5 }, size: { X: 0.3, Y: 0.2 },
      props: {
        BackgroundColor3: type === 'TextLabel' || type === 'TextButton' || type === 'TextBox' ? '#2a2a3e' : '#1a1a2e',
        TextColor3: '#ffffff', Text: type.includes('Text') || type === 'TextBox' ? (type === 'TextBox' ? '' : 'Text') : '',
        Font: 'GothamBold', TextScaled: true, TextSize: 14,
      },
      children: [], zIndex: elements.length + 1, locked: false, visible: true,
    }
    if (type === 'ScrollingFrame') { el.props.ScrollBarThickness = 8; el.props.CanvasSize = { X: 0, Y: 2 } }
    const newEls = [...elements, el]
    if (parentId) { const p = newEls.find(e => e.id === parentId); if (p) p.children = [...p.children, id] }
    setElements(newEls); pushHist(newEls); setSelectedId(id)
  }, [elements, pushHist])

  const updateEl = useCallback((id: string, patch: Partial<UIEl>) => {
    const newEls = elements.map(e => e.id === id ? { ...e, ...patch } : e)
    setElements(newEls); pushHist(newEls)
  }, [elements, pushHist])

  const updateProps = useCallback((id: string, props: Record<string, any>) => {
    const newEls = elements.map(e => e.id === id ? { ...e, props: { ...e.props, ...props } } : e)
    setElements(newEls); pushHist(newEls)
  }, [elements, pushHist])

  const removeEl = useCallback((id: string) => {
    const newEls = elements.filter(e => e.id !== id).map(e => ({ ...e, children: e.children.filter(c => c !== id) }))
    setElements(newEls); pushHist(newEls); if (selectedId === id) setSelectedId(null)
  }, [elements, selectedId, pushHist])

  const duplicateEl = useCallback((id: string) => {
    const el = elements.find(e => e.id === id); if (!el) return
    const newId = uid()
    const dup: UIEl = { ...el, id: newId, name: el.name + ' Copy', position: { X: el.position.X + 0.02, Y: el.position.Y + 0.02 }, children: [], props: { ...el.props } }
    const newEls = [...elements, dup]
    setElements(newEls); pushHist(newEls); setSelectedId(newId)
  }, [elements, pushHist])

  // Building state
  const [building, setBuilding] = useState(false)
  const [buildingId, setBuildingId] = useState<string | null>(null)
  const [buildingMsg, setBuildingMsg] = useState('')
  const buildingRef = useRef(false)
  const elementCountRef = useRef(0)

  // ─── AI Commands (synchronized, one by one) ───
  const applyCmds = useCallback(async (cmds: any[]) => {
    if (buildingRef.current) return
    buildingRef.current = true
    setBuilding(true)
    setBuildingMsg('Building...')

    // Sort: root adds first, then children, then modifies
    const sorted = [...cmds].sort((a: any, b: any) => {
      if (a.action === 'add' && !a.parent) return -1
      if (b.action === 'add' && !b.parent) return 1
      if (a.action === 'add' && b.action === 'add') return 0
      if (a.action === 'modify') return 1
      if (a.action === 'remove') return 2
      return 0
    })

    const nameToId = new Map<string, string>()
    let zCounter = elementCountRef.current

    // Check if instant mode
    const instantMode = localStorage.getItem('ui-instant-build') === 'true'
    const delay = instantMode ? 0 : 120

    for (let i = 0; i < sorted.length; i++) {
      const cmd = sorted[i]
      if (cmd.action === 'add') {
        const id = uid()
        zCounter++
        const resolvedParent = cmd.parent ? (nameToId.get(cmd.parent) || null) : null
        const el: UIEl = {
          id, type: cmd.elementType || 'Frame', name: cmd.name || `Element${zCounter}`,
          parentId: resolvedParent,
          position: cmd.position || { X: 0.5, Y: 0.5 }, size: cmd.size || { X: 0.3, Y: 0.2 },
          props: { BackgroundColor3: '#1a1a2e', TextColor3: '#ffffff', Text: '', Font: 'GothamBold', TextScaled: true, TextSize: 14, ...cmd.properties },
          children: [], zIndex: zCounter, locked: false, visible: true,
        }
        nameToId.set(el.name, id)
        setBuildingId(id)
        setBuildingMsg(`Adding ${el.name}...`)
        setElements(prev => {
          const newEls = [...prev.map(e => ({ ...e })), el]
          if (el.parentId) {
            const p = newEls.find(e => e.id === el.parentId)
            if (p) {
              const updatedParent = { ...p, children: [...p.children, id] }
              const idx = newEls.findIndex(e => e.id === el.parentId)
              newEls[idx] = updatedParent
            }
          }
          elementCountRef.current = zCounter
          return newEls
        })
        if (delay > 0) await new Promise(r => setTimeout(r, delay))
      } else if (cmd.action === 'modify') {
        setBuildingMsg(`Modifying ${cmd.target}...`)
        setElements(prev => prev.map(e => e.name.toLowerCase() === (cmd.target || '').toLowerCase() ? { ...e, props: { ...e.props, ...cmd.properties } } : e))
        if (delay > 0) await new Promise(r => setTimeout(r, 60))
      } else if (cmd.action === 'remove') {
        setBuildingMsg(`Removing ${cmd.target}...`)
        setElements(prev => {
          const idx = prev.findIndex(e => e.name.toLowerCase() === (cmd.target || '').toLowerCase())
          if (idx >= 0) { const rid = prev[idx].id; return prev.filter(e => e.id !== rid).map(e => ({ ...e, children: e.children.filter(c => c !== rid) })) }
          return prev
        })
        if (delay > 0) await new Promise(r => setTimeout(r, 60))
      }
    }

    setBuildingId(null)
    setBuildingMsg('')
    setBuilding(false)
    buildingRef.current = false
  }, [])

  const sendMsg = async (text?: string) => {
    const msg = (text || input).trim(); if (!msg || isLoading || building) return
    const um: ChatMsg = { role: 'user', content: msg }
    setMessages(p => [...p, um]); setInput(''); setIsLoading(true)
    try {
      const cs = elements.map(e => ({ name: e.name, type: e.type, pos: e.position, size: e.size }))
      const r = await fetch(CHAT_API, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: [{ role: 'user', content: msg }], canvas_state: cs }),
      })
      const d = await r.json()

      // Check for errors
      if (!r.ok || d.error) {
        setIsLoading(false)
        setMessages(p => [...p, { role: 'assistant', content: `Error: ${d.error || d.message || 'Request failed'}. Using template instead.` }])
        // Still try template fallback
        const tmplResp = await fetch(CHAT_API, {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ messages: [{ role: 'user', content: msg }], canvas_state: cs, force_template: true }),
        })
        const tmpl = await tmplResp.json()
        if (tmpl.commands?.length) {
          const am: ChatMsg = { role: 'assistant', content: tmpl.message || 'Built from template', commands: tmpl.commands }
          setMessages(p => [...p, am])
          await applyCmds(tmpl.commands)
        }
        return
      }

      const am: ChatMsg = { role: 'assistant', content: d.message || d.content || 'Done', commands: d.commands || [] }
      setMessages(p => [...p, am])

      if (am.commands?.length) {
        await applyCmds(am.commands)
      } else {
        setMessages(p => [...p, { role: 'assistant', content: 'No UI elements generated. Try describing what you want, like "shop with 4 items" or "health bar HUD".' }])
      }
      setIsLoading(false)
    } catch (e) {
      console.error('UI Builder error:', e)
      setIsLoading(false)
      setMessages(p => [...p, { role: 'assistant', content: 'Connection error. Try again.' }])
    }
  }

  // ─── Canvas Interactions ───
  const dev = DEVICES[device]
  const cw = dev.w * zoom; const ch = dev.h * zoom

  const handleCanvasDown = useCallback((e: React.MouseEvent) => {
    if (e.button === 1 || (e.button === 0 && e.altKey)) {
      setIsPanning(true); setPanStart({ x: e.clientX, y: e.clientY, px: pan.x, py: pan.y }); return
    }
    if (buildMode && selectedId && canvasRef.current) {
      const el = elements.find(x => x.id === selectedId); if (!el || el.locked) return
      const rect = canvasRef.current.getBoundingClientRect()
      const sx = (e.clientX - rect.left) / rect.width
      const sy = (e.clientY - rect.top) / rect.height
      setDragging(true)
      setDragData({ sx, sy, ox: el.position.X, oy: el.position.Y })
    }
  }, [buildMode, selectedId, elements, pan])

  const handleCanvasMove = useCallback((e: React.MouseEvent) => {
    if (isPanning) {
      setPan({ x: panStart.px + (e.clientX - panStart.x), y: panStart.py + (e.clientY - panStart.y) }); return
    }
    if (dragging && dragData && selectedId && canvasRef.current) {
      const rect = canvasRef.current.getBoundingClientRect()
      const dx = ((e.clientX - rect.left) / rect.width - dragData.sx) / zoom
      const dy = ((e.clientY - rect.top) / rect.height - dragData.sy) / zoom
      const nx = Math.max(0, Math.min(1, snap(dragData.ox + dx)))
      const ny = Math.max(0, Math.min(1, snap(dragData.oy + dy)))
      setElements(prev => prev.map(el => el.id === selectedId ? { ...el, position: { X: nx, Y: ny } } : el))
    }
    if (resizing && resizeData && selectedId && canvasRef.current) {
      const rect = canvasRef.current.getBoundingClientRect()
      const dx = ((e.clientX - rect.left) / rect.width - (resizeData.sx - rect.left) / rect.width) / zoom
      const dy = ((e.clientY - rect.top) / rect.height - (resizeData.sy - rect.top) / rect.height) / zoom
      let nw = resizeData.ow, nh = resizeData.oh
      if (resizeData.corner.includes('e')) nw = Math.max(0.01, resizeData.ow + dx)
      if (resizeData.corner.includes('s')) nh = Math.max(0.01, resizeData.oh + dy)
      setElements(prev => prev.map(el => el.id === selectedId ? { ...el, size: { X: snap(nw), Y: snap(nh) } } : el))
    }
  }, [isPanning, panStart, dragging, dragData, resizing, resizeData, selectedId, zoom, snap])

  const handleCanvasUp = useCallback(() => {
    if (dragging || resizing) pushHist(elements)
    setIsPanning(false); setDragging(false); setResizing(false); setDragData(null); setResizeData(null)
  }, [dragging, resizing, elements, pushHist])

  // Keyboard shortcuts
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.target as HTMLElement).tagName === 'INPUT' || (e.target as HTMLElement).tagName === 'TEXTAREA') return
      if (e.key === 'Delete' || e.key === 'Backspace') { if (selectedId) { e.preventDefault(); removeEl(selectedId) } }
      if (e.ctrlKey && e.key === 'z') { e.preventDefault(); undo() }
      if (e.ctrlKey && e.key === 'y') { e.preventDefault(); redo() }
      if (e.ctrlKey && e.key === 'd') { e.preventDefault(); if (selectedId) duplicateEl(selectedId) }
      if (e.key === 'Escape') setSelectedId(null)
      if (selectedId && buildMode) {
        const nudge = e.shiftKey ? 0.01 : 0.005
        const el = elements.find(x => x.id === selectedId); if (!el) return
        if (e.key === 'ArrowLeft') { e.preventDefault(); updateEl(selectedId, { position: { X: Math.max(0, el.position.X - nudge), Y: el.position.Y } }) }
        if (e.key === 'ArrowRight') { e.preventDefault(); updateEl(selectedId, { position: { X: Math.min(1, el.position.X + nudge), Y: el.position.Y } }) }
        if (e.key === 'ArrowUp') { e.preventDefault(); updateEl(selectedId, { position: { X: el.position.X, Y: Math.max(0, el.position.Y - nudge) } }) }
        if (e.key === 'ArrowDown') { e.preventDefault(); updateEl(selectedId, { position: { X: el.position.X, Y: Math.min(1, el.position.Y + nudge) } }) }
      }
    }
    window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler)
  }, [selectedId, buildMode, elements, removeEl, updateEl, undo, redo, duplicateEl])

  const suggestedPrompts = [
    'Shop with 4 items, prices, and buy buttons',
    'Main menu with play, settings, credits buttons',
    'Health and mana bar HUD at bottom of screen',
    'Inventory grid with 12 item slots',
    'Character stats panel with avatar and level',
    'Chat box with messages and input field',
    'Quest tracker on the right side with progress bars',
    'Settings panel with toggles and sliders',
  ]

  const quickPresets = [
    { label: 'Shop', emoji: '🛒', prompt: 'Shop with 4 items, prices, and buy buttons' },
    { label: 'Menu', emoji: '🎮', prompt: 'Main menu with play, settings, credits buttons' },
    { label: 'HUD', emoji: '❤️', prompt: 'Health and mana bar HUD at bottom of screen' },
    { label: 'Inventory', emoji: '🎒', prompt: 'Inventory grid with 12 item slots' },
    { label: 'Stats', emoji: '⚔️', prompt: 'Character stats panel with avatar and level' },
    { label: 'Chat', emoji: '💬', prompt: 'Chat box with messages and input field' },
  ]

  // ─── Element Style ───
  function elStyle(el: UIEl): React.CSSProperties {
    const p = el.props
    return {
      position: 'absolute', left: `${el.position.X * 100}%`, top: `${el.position.Y * 100}%`,
      width: `${el.size.X * 100}%`, height: `${el.size.Y * 100}%`,
      transform: `translate(-50%, -50%)${p.Rotation ? ` rotate(${p.Rotation}deg)` : ''}`,
      backgroundColor: (p.BackgroundTransparency ?? 0) >= 1 ? 'transparent' : parseColor(p.BackgroundColor3),
      borderRadius: p.CornerRadius || 0,
      border: p.BorderSizePixel > 0 ? `${p.BorderSizePixel}px solid ${parseColor(p.BorderColor3)}` : undefined,
      zIndex: el.zIndex || 1, overflow: el.type === 'ScrollingFrame' ? 'auto' : 'hidden',
      opacity: el.visible ? 1 : 0.3, outline: selectedId === el.id ? '2px solid #3b82f6' : undefined,
      outlineOffset: '1px',
    }
  }

  function childStyle(el: UIEl): React.CSSProperties {
    const p = el.props
    return {
      position: 'absolute', left: `${el.position.X * 100}%`, top: `${el.position.Y * 100}%`,
      width: `${el.size.X * 100}%`, height: `${el.size.Y * 100}%`,
      transform: 'translate(-50%, -50%)',
      backgroundColor: (p.BackgroundTransparency ?? 0) >= 1 ? 'transparent' : parseColor(p.BackgroundColor3),
      borderRadius: p.CornerRadius || 0, zIndex: el.zIndex || 1, overflow: 'hidden',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      border: p.BorderSizePixel > 0 ? `${p.BorderSizePixel}px solid ${parseColor(p.BorderColor3)}` : undefined,
    }
  }

  // ─── Render ───
  const roots = elements.filter(e => !e.parentId)

  return (
    <div className="flex flex-col rounded-2xl bg-bg-secondary border border-border-primary overflow-hidden" style={{ height: '75vh', minHeight: 650 }}>

      {/* ─── Top Bar ─── */}
      <div className="flex items-center gap-2 px-3 py-2 border-b border-border-primary bg-bg-elevated/80">
        <div className="flex items-center gap-1.5">
          <Sparkles size={14} className="text-accent-purple" />
          <span className="text-xs font-bold text-text-primary">UI Builder</span>
        </div>
        <div className="h-4 w-px bg-border-primary" />

        {/* Device Preview */}
        <div className="flex items-center gap-0.5 p-0.5 bg-bg-secondary rounded-lg border border-border-primary">
          {DEVICES.map((d, i) => {
            const Icon = d.icon
            return (
              <button key={i} onClick={() => setDevice(i)} title={d.name}
                className={cn('p-1.5 rounded-md transition-all', device === i ? 'bg-accent-blue/15 text-accent-blue' : 'text-text-dim hover:text-text-muted')}>
                <Icon size={13} />
              </button>
            )
          })}
        </div>
        <span className="text-[10px] text-text-dim font-mono">{dev.w}×{dev.h}</span>

        <div className="h-4 w-px bg-border-primary" />

        {/* Tools */}
        <button onClick={() => setBuildMode(!buildMode)} className={cn('flex items-center gap-1 px-2 py-1 rounded-md text-[10px] font-medium transition-all', buildMode ? 'bg-green-500/10 text-green-400 border border-green-500/20' : 'text-text-dim hover:text-text-muted border border-transparent')}>
          <MousePointer2 size={11} /> Select
        </button>
        <button onClick={() => setShowGrid(!showGrid)} className={cn('flex items-center gap-1 px-2 py-1 rounded-md text-[10px] font-medium transition-all', showGrid ? 'bg-accent-purple/10 text-accent-purple border border-accent-purple/20' : 'text-text-dim hover:text-text-muted border border-transparent')}>
          <Grid3X3 size={11} /> Grid
        </button>
        <button onClick={() => setSnapToGrid(!snapToGrid)} className={cn('flex items-center gap-1 px-2 py-1 rounded-md text-[10px] font-medium transition-all', snapToGrid ? 'bg-accent-orange/10 text-accent-orange border border-accent-orange/20' : 'text-text-dim hover:text-text-muted border border-transparent')}>
          Snap
        </button>
        <button onClick={() => setInstantBuild(!instantBuild)} className={cn('flex items-center gap-1 px-2 py-1 rounded-md text-[10px] font-medium transition-all', instantBuild ? 'bg-green-500/10 text-green-400 border border-green-500/20' : 'text-text-dim hover:text-text-muted border border-transparent')} title="Skip animation, build instantly">
          <Zap size={11} /> Instant
        </button>

        <div className="h-4 w-px bg-border-primary" />

        {/* Zoom */}
        <button onClick={() => setZoom(z => Math.min(1.5, z + 0.1))} className="p-1 rounded text-text-dim hover:text-text-muted"><ZoomIn size={12} /></button>
        <span className="text-[10px] text-text-dim w-8 text-center font-mono">{Math.round(zoom * 100)}%</span>
        <button onClick={() => setZoom(z => Math.max(0.2, z - 0.1))} className="p-1 rounded text-text-dim hover:text-text-muted"><ZoomOut size={12} /></button>
        <button onClick={() => { setZoom(0.55); setPan({ x: 0, y: 0 }) }} className="p-1 rounded text-text-dim hover:text-text-muted"><RotateCcw size={11} /></button>

        <div className="flex-1" />

        {/* Add + Export */}
        <div className="flex items-center gap-1">
          {ELEMENT_TYPES.map(et => (
            <button key={et.type} onClick={() => addEl(et.type, selectedId)} title={`Add ${et.label}`}
              className="px-2 py-1 rounded-md text-[10px] text-text-dim hover:text-text-primary hover:bg-bg-secondary border border-transparent hover:border-border-hover transition-all">
              + {et.desc}
            </button>
          ))}
        </div>

        <button onClick={() => setShowImageSearch(true)} className="p-1.5 rounded-md text-text-dim hover:text-text-muted hover:bg-bg-secondary transition-all"><ImageIcon size={12} /></button>
        <button onClick={() => setShowExport(true)} className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[10px] font-semibold bg-accent-purple/15 text-accent-purple border border-accent-purple/20 hover:bg-accent-purple/25 transition-all">
          <Download size={11} /> Export
        </button>
      </div>

      {/* ─── Main Area ─── */}
      <div className="flex-1 flex min-h-0">

        {/* ─── Layers Panel ─── */}
        {showLayers && (
          <div className="w-52 border-r border-border-primary flex flex-col bg-bg-primary/30">
            <div className="flex items-center justify-between px-3 py-2 border-b border-border-primary">
              <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider">Layers</span>
              <span className="text-[10px] text-text-dim">{elements.length}</span>
            </div>
            <div className="flex-1 overflow-y-auto py-1">
              {elements.length === 0 && <p className="px-3 py-4 text-[10px] text-text-dim text-center">No elements yet</p>}
              {[...elements].reverse().map(el => (
                <div key={el.id}
                  className={cn('flex items-center gap-1.5 px-2 py-1 cursor-pointer transition-all group',
                    selectedId === el.id ? 'bg-accent-blue/10 text-accent-blue' : 'text-text-secondary hover:bg-bg-elevated')}
                  onClick={() => setSelectedId(el.id)}
                  style={{ paddingLeft: `${12 + (el.parentId ? 16 : 0)}px` }}>
                  <span className="text-[10px] text-text-dim w-3">{el.type === 'Frame' ? '▬' : el.type === 'TextLabel' ? 'Aa' : el.type === 'TextButton' ? '☐' : el.type === 'ImageLabel' ? '🖼' : el.type === 'ScrollingFrame' ? '☰' : '□'}</span>
                  <span className="flex-1 text-[10px] truncate font-medium">{el.name}</span>
                  <button onClick={(e) => { e.stopPropagation(); updateEl(el.id, { visible: !el.visible }) }} className="opacity-0 group-hover:opacity-100 p-0.5 transition-opacity">
                    {el.visible ? <Eye size={9} className="text-text-dim" /> : <EyeOff size={9} className="text-red-400" />}
                  </button>
                  <button onClick={(e) => { e.stopPropagation(); updateEl(el.id, { locked: !el.locked }) }} className="opacity-0 group-hover:opacity-100 p-0.5 transition-opacity">
                    {el.locked ? <Lock size={9} className="text-yellow-400" /> : <Unlock size={9} className="text-text-dim" />}
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ─── Canvas ─── */}
        <div className="flex-1 overflow-hidden bg-[#08080c] relative"
          onMouseDown={handleCanvasDown} onMouseMove={handleCanvasMove} onMouseUp={handleCanvasUp} onMouseLeave={handleCanvasUp}
          onClick={() => setSelectedId(null)} style={{ cursor: isPanning ? 'grabbing' : 'default' }}>
          <div ref={canvasRef} className="absolute" style={{
            width: cw, height: ch,
            left: `calc(50% + ${pan.x}px)`, top: `calc(50% + ${pan.y}px)`,
            transform: 'translate(-50%, -50%)',
          }}>
            {/* Grid */}
            {showGrid && (
              <div className="absolute inset-0 pointer-events-none rounded-lg" style={{
                backgroundImage: 'linear-gradient(rgba(255,255,255,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.04) 1px, transparent 1px)',
                backgroundSize: `${cw / (dev.w / gridSize)}px ${ch / (dev.h / gridSize)}px`
              }} />
            )}
            {/* Screen */}
            <div className="absolute inset-0 bg-[#1a1a2e] rounded-lg border border-white/5 shadow-2xl overflow-hidden">
              {/* Recursive element renderer */}
              {(() => {
                const renderEl = (el: UIEl, isChild = false): React.ReactNode => {
                  if (!el.visible) return null
                  const childEls = el.children.map(cid => elements.find(e => e.id === cid)).filter(Boolean) as UIEl[]
                  const isBuilding = buildingId === el.id
                  return (
                    <div key={el.id} style={isChild ? childStyle(el) : elStyle(el)}
                      className={cn('cursor-pointer select-none', isBuilding && 'el-building')}
                      onClick={(e) => { e.stopPropagation(); setSelectedId(el.id) }}
                      onMouseDown={(e) => { e.stopPropagation(); if (buildMode && !el.locked) { setSelectedId(el.id); handleCanvasDown(e) } }}>
                      {childEls.map(child => renderEl(child, true))}
                      {(el.type === 'TextLabel' || el.type === 'TextButton' || el.type === 'TextBox') && childEls.length === 0 && (
                        <span style={{ color: parseColor(el.props.TextColor3), fontSize: el.props.TextScaled ? undefined : (el.props.TextSize || 14), textAlign: el.props.TextXAlignment === 'Left' ? 'left' : el.props.TextXAlignment === 'Right' ? 'right' : 'center' }} className="px-2 font-bold truncate w-full block">{el.props.Text || (el.type === 'TextBox' ? 'Input...' : 'Text')}</span>
                      )}
                      {el.type === 'ImageLabel' && el.props.Image && childEls.length === 0 && (
                        <img src={el.props.Image} alt="" className="w-full h-full object-cover" style={{ opacity: 1 - (el.props.ImageTransparency || 0) }} />
                      )}
                      {el.type === 'ScrollingFrame' && childEls.length === 0 && (
                        <div className="absolute inset-0 flex items-center justify-center text-white/10 text-[9px]">Scroll Area</div>
                      )}
                    </div>
                  )
                }
                return roots.map(el => renderEl(el, false))
              })()}
              {elements.length === 0 && (
                <div className="absolute inset-0 flex flex-col items-center justify-center text-white/15 pointer-events-none">
                  <Layers size={36} className="mb-2 opacity-30" />
                  <p className="text-xs font-medium">Empty Canvas</p>
                  <p className="text-[10px] opacity-50">Use AI chat or + buttons to add elements</p>
                </div>
              )}
            </div>
            {/* Resize handles */}
            {selected && buildMode && !selected.locked && (
              <>
                {['nw', 'ne', 'sw', 'se'].map(c => (
                  <div key={c} className={cn('absolute w-3 h-3 bg-white border-2 border-accent-blue rounded-full z-50 shadow-lg',
                    c === 'nw' && '-top-1.5 -left-1.5 cursor-nw-resize', c === 'ne' && '-top-1.5 -right-1.5 cursor-ne-resize',
                    c === 'sw' && '-bottom-1.5 -left-1.5 cursor-sw-resize', c === 'se' && '-bottom-1.5 -right-1.5 cursor-se-resize'
                  )} style={{ left: c.includes('w') ? `${selected.position.X * 100 - 1}%` : undefined, right: c.includes('e') ? `${(1 - selected.position.X) * 100 - 1}%` : undefined, top: c.includes('n') ? `${selected.position.Y * 100 - 1}%` : undefined, bottom: c.includes('s') ? `${(1 - selected.position.Y) * 100 - 1}%` : undefined, position: 'absolute' }}
                    onMouseDown={(e) => { e.stopPropagation(); setResizing(true); setResizeData({ sx: e.clientX, sy: e.clientY, ow: selected.size.X, oh: selected.size.Y, corner: c }) }} />
                ))}
              </>
            )}
          </div>
          {/* Building progress */}
          {building && (
            <div className="absolute top-3 left-1/2 -translate-x-1/2 z-40 flex items-center gap-2 px-4 py-2 rounded-xl bg-black/70 backdrop-blur-md border border-accent-purple/30 shadow-lg shadow-accent-purple/10">
              <div className="w-2 h-2 rounded-full bg-accent-purple animate-pulse" />
              <span className="text-[11px] text-white/90 font-medium">{buildingMsg}</span>
            </div>
          )}
          {/* Keyboard hints */}
          <div className="absolute bottom-2 left-2 flex gap-1.5 text-[9px] text-white/15 pointer-events-none">
            <span>Arrow: nudge</span><span>Shift+Arrow: fast</span><span>Del: remove</span><span>Ctrl+Z: undo</span><span>Alt+Drag: pan</span>
          </div>
        </div>

        {/* ─── Right Panel: Properties + Chat ─── */}
        <div className="w-[320px] border-l border-border-primary flex flex-col bg-bg-primary/30">
          {/* Properties */}
          {selected && showProps && (
            <div className="border-b border-border-primary max-h-[45%] overflow-y-auto">
              <div className="flex items-center justify-between px-3 py-2 sticky top-0 bg-bg-elevated/90 backdrop-blur-sm z-10">
                <div className="flex items-center gap-2">
                  <Settings size={11} className="text-text-dim" />
                  <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider">{selected.type}</span>
                  <span className="text-[10px] text-text-dim">{selected.name}</span>
                </div>
                <div className="flex items-center gap-1">
                  <button onClick={() => duplicateEl(selected.id)} className="p-1 rounded hover:bg-bg-secondary text-text-dim hover:text-text-muted"><Copy size={10} /></button>
                  <button onClick={() => removeEl(selected.id)} className="p-1 rounded hover:bg-red-500/10 text-text-dim hover:text-red-400"><Trash2 size={10} /></button>
                </div>
              </div>
              {/* Name */}
              <div className="px-3 py-1.5 border-b border-border-primary/50">
                <label className="text-[9px] text-text-dim block mb-0.5">Name</label>
                <input value={selected.name} onChange={e => updateEl(selected.id, { name: e.target.value })}
                  className="w-full px-2 py-1 rounded bg-bg-secondary border border-border-primary text-[10px] text-text-primary focus:outline-none focus:border-accent-blue/50" />
              </div>
              {/* Position */}
              <div className="px-3 py-1.5 border-b border-border-primary/50 flex gap-2">
                <div className="flex-1">
                  <label className="text-[9px] text-text-dim block mb-0.5">Pos X</label>
                  <input type="number" step="0.01" min="0" max="1" value={+selected.position.X.toFixed(3)}
                    onChange={e => updateEl(selected.id, { position: { ...selected.position, X: Math.max(0, Math.min(1, parseFloat(e.target.value) || 0)) } })}
                    className="w-full px-2 py-1 rounded bg-bg-secondary border border-border-primary text-[10px] text-text-primary font-mono focus:outline-none focus:border-accent-blue/50" />
                </div>
                <div className="flex-1">
                  <label className="text-[9px] text-text-dim block mb-0.5">Pos Y</label>
                  <input type="number" step="0.01" min="0" max="1" value={+selected.position.Y.toFixed(3)}
                    onChange={e => updateEl(selected.id, { position: { ...selected.position, Y: Math.max(0, Math.min(1, parseFloat(e.target.value) || 0)) } })}
                    className="w-full px-2 py-1 rounded bg-bg-secondary border border-border-primary text-[10px] text-text-primary font-mono focus:outline-none focus:border-accent-blue/50" />
                </div>
              </div>
              {/* Size */}
              <div className="px-3 py-1.5 border-b border-border-primary/50 flex gap-2">
                <div className="flex-1">
                  <label className="text-[9px] text-text-dim block mb-0.5">Size X</label>
                  <input type="number" step="0.01" min="0.01" max="1" value={+selected.size.X.toFixed(3)}
                    onChange={e => updateEl(selected.id, { size: { ...selected.size, X: Math.max(0.01, Math.min(1, parseFloat(e.target.value) || 0.01)) } })}
                    className="w-full px-2 py-1 rounded bg-bg-secondary border border-border-primary text-[10px] text-text-primary font-mono focus:outline-none focus:border-accent-blue/50" />
                </div>
                <div className="flex-1">
                  <label className="text-[9px] text-text-dim block mb-0.5">Size Y</label>
                  <input type="number" step="0.01" min="0.01" max="1" value={+selected.size.Y.toFixed(3)}
                    onChange={e => updateEl(selected.id, { size: { ...selected.size, Y: Math.max(0.01, Math.min(1, parseFloat(e.target.value) || 0.01)) } })}
                    className="w-full px-2 py-1 rounded bg-bg-secondary border border-border-primary text-[10px] text-text-primary font-mono focus:outline-none focus:border-accent-blue/50" />
                </div>
              </div>
              {/* Property Groups */}
              {Object.entries(PROP_GROUPS).map(([group, keys]) => {
                const relevant = keys.filter(k => {
                  if (['Text', 'TextColor3', 'TextTransparency', 'TextScaled', 'Font', 'TextSize', 'TextWrapped', 'TextXAlignment', 'TextYAlignment', 'RichText'].includes(k) && !selected.type.includes('Text') && selected.type !== 'TextBox') return false
                  if (['Image', 'ImageColor3', 'ImageTransparency'].includes(k) && !['ImageLabel', 'ImageButton'].includes(selected.type)) return false
                  if (['CornerRadius'].includes(k) && !['Frame', 'TextLabel', 'TextButton', 'ImageLabel', 'ScrollingFrame', 'TextBox'].includes(selected.type)) return false
                  if (['ScrollBarThickness', 'ScrollBarImageColor3', 'CanvasSize', 'AutomaticCanvasSize'].includes(k) && selected.type !== 'ScrollingFrame') return false
                  return true
                })
                if (relevant.length === 0) return null
                const expanded = expandedGroups.has(group)
                return (
                  <div key={group} className="border-b border-border-primary/50">
                    <button onClick={() => { const s = new Set(expandedGroups); expanded.has(s.delete(group)) ? s.add(group) : null; setExpandedGroups(s) }}
                      className="w-full flex items-center gap-1.5 px-3 py-1.5 text-[9px] font-bold text-text-dim uppercase tracking-wider hover:bg-bg-elevated transition-all">
                      {expanded ? <ChevronDown size={9} /> : <ChevronRight size={9} />}{group}
                    </button>
                    {expanded && relevant.map(k => {
                      const val = selected.props[k]
                      const isColor = k.toLowerCase().includes('color') || k === 'BackgroundColor3' || k === 'TextColor3' || k === 'BorderColor3' || k === 'ImageColor3' || k === 'ScrollBarImageColor3'
                      return (
                        <div key={k} className="flex items-center gap-2 px-3 py-1">
                          <label className="text-[9px] text-text-dim w-20 shrink-0 truncate">{k}</label>
                          {isColor ? (
                            <div className="flex items-center gap-1 flex-1">
                              <input type="color" value={parseColor(val)} onChange={e => updateProps(selected.id, { [k]: e.target.value })}
                                className="w-5 h-5 rounded border border-border-primary cursor-pointer" />
                              <input value={parseColor(val)} onChange={e => updateProps(selected.id, { [k]: e.target.value })}
                                className="flex-1 px-1.5 py-0.5 rounded bg-bg-secondary border border-border-primary text-[9px] text-text-primary font-mono focus:outline-none focus:border-accent-blue/50" />
                            </div>
                          ) : typeof val === 'boolean' ? (
                            <button onClick={() => updateProps(selected.id, { [k]: !val })}
                              className={cn('px-2 py-0.5 rounded text-[9px] font-medium transition-all', val ? 'bg-green-500/15 text-green-400' : 'bg-bg-secondary text-text-dim')}>
                              {val ? 'True' : 'False'}
                            </button>
                          ) : typeof val === 'number' ? (
                            <input type="number" step="1" value={val}
                              onChange={e => updateProps(selected.id, { [k]: parseFloat(e.target.value) || 0 })}
                              className="flex-1 px-1.5 py-0.5 rounded bg-bg-secondary border border-border-primary text-[9px] text-text-primary font-mono focus:outline-none focus:border-accent-blue/50" />
                          ) : (
                            <input value={String(val ?? '')}
                              onChange={e => updateProps(selected.id, { [k]: e.target.value })}
                              className="flex-1 px-1.5 py-0.5 rounded bg-bg-secondary border border-border-primary text-[9px] text-text-primary font-mono focus:outline-none focus:border-accent-blue/50" />
                          )}
                        </div>
                      )
                    })}
                  </div>
                )
              })}
            </div>
          )}

          {/* AI Chat */}
          <div className={cn('flex-1 flex flex-col min-h-0', !selected && 'h-full')}>
            <div className="flex items-center justify-between px-3 py-2 border-b border-border-primary">
              <div className="flex items-center gap-2">
                <div className="w-5 h-5 rounded bg-gradient-to-br from-accent-purple to-accent-pink flex items-center justify-center"><Sparkles size={10} className="text-white" /></div>
                <span className="text-[10px] font-bold text-text-muted">AI Assistant</span>
              </div>
              {messages.length > 0 && (
                <button onClick={() => setMessages([])} className="text-[9px] text-text-dim hover:text-text-muted transition-all">Clear</button>
              )}
            </div>
            <div className="flex-1 overflow-y-auto px-3 py-2 space-y-2">
              {messages.length === 0 && (
                <div className="flex flex-col items-center justify-center h-full text-center px-2">
                  <Sparkles size={20} className="text-accent-purple/30 mb-2" />
                  <p className="text-[10px] text-text-dim mb-3">Describe your UI and AI builds it on the canvas</p>
                  <div className="grid grid-cols-3 gap-1.5 mb-3 w-full">
                    {quickPresets.map((p, i) => (
                      <button key={i} onClick={() => sendMsg(p.prompt)}
                        className="flex flex-col items-center gap-0.5 px-2 py-2 rounded-lg text-[10px] text-text-dim bg-bg-elevated border border-border-primary hover:border-accent-purple/40 hover:text-accent-purple hover:bg-accent-purple/5 transition-all">
                        <span className="text-base">{p.emoji}</span>
                        <span className="font-medium">{p.label}</span>
                      </button>
                    ))}
                  </div>
                  <div className="flex flex-wrap gap-1 justify-center">
                    {suggestedPrompts.slice(0, 4).map((p, i) => (
                      <button key={i} onClick={() => sendMsg(p)} className="px-2 py-1 rounded-md text-[9px] text-text-dim bg-bg-elevated border border-border-primary hover:border-accent-purple/30 hover:text-accent-purple transition-all">{p}</button>
                    ))}
                  </div>
                </div>
              )}
              {messages.map((msg, i) => (
                <div key={i} className={cn('flex', msg.role === 'user' ? 'justify-end' : 'justify-start')}>
                  <div className={cn('max-w-[90%] px-2.5 py-1.5 rounded-lg text-[10px] leading-relaxed',
                    msg.role === 'user' ? 'bg-accent-blue text-white rounded-br-sm' : 'bg-bg-elevated text-text-primary rounded-bl-sm border border-border-primary')}>
                    <p className="whitespace-pre-wrap break-words">{msg.content}</p>
                    {msg.commands?.length ? (
                      <div className="mt-1 flex flex-wrap gap-0.5">
                        {msg.commands.map((c: any, j: number) => (
                          <span key={j} className={cn('px-1 py-0.5 rounded text-[8px] font-mono', c.action === 'add' && 'bg-green-500/10 text-green-400', c.action === 'modify' && 'bg-yellow-500/10 text-yellow-400', c.action === 'remove' && 'bg-red-500/10 text-red-400')}>
                            {c.action} {c.name || c.target || c.elementType}
                          </span>
                        ))}
                      </div>
                    ) : null}
                  </div>
                </div>
              ))}
              {isLoading && (
                <div className="flex justify-start"><div className="bg-bg-elevated border border-border-primary rounded-lg px-3 py-1.5"><div className="flex gap-1"><span className="w-1 h-1 rounded-full bg-accent-purple animate-bounce" /><span className="w-1 h-1 rounded-full bg-accent-purple animate-bounce" style={{ animationDelay: '150ms' }} /><span className="w-1 h-1 rounded-full bg-accent-purple animate-bounce" style={{ animationDelay: '300ms' }} /></div></div></div>
              )}
              <div ref={messagesEndRef} />
            </div>
            <div className="px-3 pb-2 pt-1 border-t border-border-primary">
              <div className="flex items-end gap-1.5 bg-bg-elevated rounded-lg px-2.5 py-1.5 border border-border-primary focus-within:border-accent-purple/50 transition-colors">
                <textarea value={input} onChange={e => setInput(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMsg() } }}
                  placeholder="Describe your UI..." rows={1}
                  className="flex-1 bg-transparent text-text-primary text-[10px] resize-none focus:outline-none placeholder:text-text-dim max-h-16" />
                <button onClick={() => sendMsg()} disabled={!input.trim() || isLoading || building}
                  className={cn('h-6 w-6 rounded-md flex-shrink-0 flex items-center justify-center transition-all', input.trim() && !isLoading && !building ? 'bg-accent-purple text-white' : 'bg-bg-tertiary text-text-dim')}>
                  {isLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Send className="h-3 w-3" />}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ─── Export Modal ─── */}
      {showExport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={() => setShowExport(false)}>
          <div className="bg-bg-elevated border border-border-primary rounded-2xl shadow-2xl w-[420px] flex flex-col" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-3 border-b border-border-primary">
              <h3 className="text-sm font-bold text-text-primary">Export UI ({elements.length} elements)</h3>
              <button onClick={() => setShowExport(false)} className="p-1 rounded-lg hover:bg-bg-secondary"><X size={14} className="text-text-muted" /></button>
            </div>
            <div className="p-4 space-y-2">
              {[
                { label: 'Lua Script', desc: 'Paste into Roblox Studio Command Bar', icon: FileCode2, color: 'green', fn: () => { navigator.clipboard.writeText(genLua(elements)); setShowExport(false) } },
                { label: 'Download .lua', desc: 'LocalScript file for StarterGui', icon: Download, color: 'blue', fn: () => { const b = new Blob([genLua(elements)], { type: 'text/plain' }); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href = u; a.download = 'GeneratedUI.lua'; a.click(); setShowExport(false) } },
                { label: 'Download .rbxmx', desc: 'Import via Studio → Insert from File', icon: FileJson, color: 'purple', fn: () => { const b = new Blob([genRbxmx(elements)], { type: 'application/xml' }); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href = u; a.download = 'GeneratedUI.rbxmx'; a.click(); setShowExport(false) } },
                { label: 'JSON Project', desc: 'Re-import to continue editing', icon: FileJson, color: 'orange', fn: () => { const b = new Blob([genJSON(elements)], { type: 'application/json' }); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href = u; a.download = 'UIProject.json'; a.click(); setShowExport(false) } },
              ].map((item, i) => (
                <button key={i} onClick={item.fn}
                  className="w-full flex items-center gap-3 p-3 rounded-xl bg-bg-secondary border border-border-primary hover:border-accent-blue/30 transition-all text-left group">
                  <div className={`w-9 h-9 rounded-xl bg-${item.color === 'green' ? 'accent-green' : item.color === 'blue' ? 'accent-blue' : item.color === 'purple' ? 'accent-purple' : 'accent-orange'}/10 flex items-center justify-center`}>
                    <item.icon size={16} className={`text-${item.color === 'green' ? 'accent-green' : item.color === 'blue' ? 'accent-blue' : item.color === 'purple' ? 'accent-purple' : 'accent-orange'}`} />
                  </div>
                  <div>
                    <p className="text-xs font-semibold text-text-primary group-hover:text-accent-blue transition-colors">{item.label}</p>
                    <p className="text-[10px] text-text-dim">{item.desc}</p>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ─── Image Search Modal ─── */}
      {showImageSearch && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={() => setShowImageSearch(false)}>
          <div className="bg-bg-elevated border border-border-primary rounded-2xl shadow-2xl w-[400px]" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-3 border-b border-border-primary">
              <h3 className="text-sm font-bold text-text-primary">Add Image</h3>
              <button onClick={() => setShowImageSearch(false)} className="p-1 rounded-lg hover:bg-bg-secondary"><X size={14} className="text-text-muted" /></button>
            </div>
            <div className="p-4 space-y-3">
              <input value={imageUrl} onChange={e => setImageUrl(e.target.value)} placeholder="Paste image URL..."
                className="w-full px-3 py-2 rounded-xl bg-bg-secondary border border-border-primary text-xs text-text-primary placeholder:text-text-dim focus:outline-none focus:border-accent-purple/50" />
              <div className="flex gap-2">
                <button onClick={() => { if (imageUrl) { addEl('ImageLabel'); const last = elements.length; setTimeout(() => { setElements(prev => { const n = [...prev]; const l = n[n.length - 1]; if (l) l.props.Image = imageUrl; return n }) }, 0); setImageUrl(''); setShowImageSearch(false) } }}
                  className="flex-1 px-4 py-2 rounded-xl bg-accent-purple text-white text-xs font-medium hover:bg-purple-600 transition-all">Add to Canvas</button>
                <label className="px-4 py-2 rounded-xl bg-bg-secondary border border-border-primary text-xs text-text-muted hover:text-text-primary cursor-pointer transition-all">
                  <Upload size={11} className="inline mr-1" />Upload
                  <input type="file" accept="image/*" className="hidden" onChange={e => {
                    const f = e.target.files?.[0]; if (f) { addEl('ImageLabel'); const url = URL.createObjectURL(f); setTimeout(() => { setElements(prev => { const n = [...prev]; const l = n[n.length - 1]; if (l) l.props.Image = url; return n }) }, 0); setShowImageSearch(false) }
                  }} />
                </label>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
