import { useState, useRef, useEffect, useCallback, useMemo } from 'react'
import { Send, Loader2, Sparkles, Box, Plus, Trash2, Move, MousePointer2, Download, FileCode2, FileJson, Grid3X3, ZoomIn, ZoomOut, RotateCcw, Upload, Image as ImageIcon, Wand2, X, ChevronDown, Search, Maximize2 } from 'lucide-react'
import { cn } from '@/lib/utils'
import { supabaseUrl } from '@/config/supabase'

const CHAT_API = `${supabaseUrl}/functions/v1/rodin-api?action=ui-generate`

const ELEMENT_TYPES = [
  { type: 'Frame', icon: '▬', desc: 'Container frame' },
  { type: 'TextLabel', icon: 'Aa', desc: 'Text display' },
  { type: 'TextButton', icon: '[ ]', desc: 'Clickable button' },
  { type: 'ImageLabel', icon: '🖼', desc: 'Image display' },
  { type: 'ScrollingFrame', icon: '📋', desc: 'Scrollable container' },
]

interface UIElement {
  id: string
  type: string
  name: string
  parentId: string | null
  position: { X: number; Y: number }
  size: { X: number; Y: number }
  properties: Record<string, any>
  children: string[]
  zIndex: number
}

interface ChatMessage { role: 'user' | 'assistant'; content: string; commands?: any[] }
interface ActionLogEntry { type: 'add' | 'modify' | 'remove' | 'info' | 'error'; message: string; time: number }

let idCounter = 0
const genId = () => `el_${++idCounter}_${Date.now()}`

const CANVAS_W = 1280
const CANVAS_H = 720

function parseColor(c: any): string {
  if (!c) return '#3c3c3c'
  if (typeof c === 'string' && c.startsWith('#')) return c
  if (typeof c === 'object' && c.R !== undefined) {
    const r = Math.round((c.R || 0) * 255)
    const g = Math.round((c.G || 0) * 255)
    const b = Math.round((c.B || 0) * 255)
    return `rgb(${r},${g},${b})`
  }
  return String(c)
}

function toLua(obj: any, indent = 0): string {
  const pad = '  '.repeat(indent)
  let lines: string[] = []
  if (typeof obj === 'string') return `"${obj.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
  if (typeof obj === 'number') return String(obj)
  if (typeof obj === 'boolean') return obj ? 'true' : 'false'
  if (obj && typeof obj === 'object') {
    if (Array.isArray(obj)) {
      lines.push('{')
      obj.forEach((v, i) => { lines.push(`${pad}  ${toLua(v, indent + 1)}${i < obj.length - 1 ? ',' : ''}`) })
      lines.push(`${pad}}`)
    } else {
      const keys = Object.keys(obj)
      if (keys.length === 0) return '{}'
      lines.push('{')
      keys.forEach((k, i) => {
        const val = toLua(obj[k], indent + 1)
        lines.push(`${pad}  ${k} = ${val}${i < keys.length - 1 ? ',' : ''}`)
      })
      lines.push(`${pad}}`)
    }
    return lines.join('\n')
  }
  return String(obj)
}

function generateLua(elements: UIElement[]): string {
  const lines: string[] = ['-- Generated by Yobest UI Builder', '-- Paste into Roblox Studio Command Bar or a LocalScript', '', 'local screenGui = Instance.new("ScreenGui")', 'screenGui.Name = "GeneratedUI"', 'screenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")', '']
  const elMap = new Map(elements.map(e => [e.id, e]))

  function emit(el: UIElement, parentVar: string) {
    const varName = el.name.replace(/[^a-zA-Z0-9_]/g, '_')
    const className = el.type === 'UICorner' ? 'UICorner' : el.type === 'UIStroke' ? 'UIStroke' : el.type === 'UIGradient' ? 'UIGradient' : el.type
    lines.push(`local ${varName} = Instance.new("${className}")`)
    lines.push(`${varName}.Name = "${el.name}"`)

    const props = { ...el.properties }
    props.Position = `UDim2.new(${el.position.X}, 0, ${el.position.Y}, 0)`
    props.Size = `UDim2.new(${el.size.X}, 0, ${el.size.Y}, 0)`

    for (const [k, v] of Object.entries(props)) {
      if (k === 'BackgroundColor3' || k === 'TextColor3' || k === 'BorderColor3' || k === 'ImageColor3') {
        const c = parseColor(v)
        const m = c.match(/rgb\((\d+),(\d+),(\d+)\)/)
        if (m) lines.push(`${varName}.${k} = Color3.new(${Math.round(+m[1]/255*100)/100}, ${Math.round(+m[2]/255*100)/100}, ${Math.round(+m[3]/255*100)/100})`)
        else if (v && typeof v === 'string' && v.startsWith('#')) {
          const hex = v.slice(1)
          const r = parseInt(hex.slice(0, 2), 16) / 255
          const g = parseInt(hex.slice(2, 4), 16) / 255
          const b = parseInt(hex.slice(4, 6), 16) / 255
          lines.push(`${varName}.${k} = Color3.new(${Math.round(r*100)/100}, ${Math.round(g*100)/100}, ${Math.round(b*100)/100})`)
        }
      } else if (k === 'CornerRadius') {
        lines.push(`${varName}.CornerRadius = UDim.new(0, ${v})`)
      } else if (k === 'AnchorPoint' && typeof v === 'object') {
        lines.push(`${varName}.AnchorPoint = Vector2.new(${v.X || 0}, ${v.Y || 0})`)
      } else if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        lines.push(`${varName}.${k} = ${toLua(v)}`)
      }
    }
    lines.push(`${varName}.Parent = ${parentVar}`)
    lines.push('')

    for (const cid of el.children) {
      const child = elMap.get(cid)
      if (child) emit(child, varName)
    }
  }

  const roots = elements.filter(e => !e.parentId)
  for (const root of roots) emit(root, 'screenGui')

  lines.push('')
  lines.push('print("UI Generated successfully!")')
  return lines.join('\n')
}

function generateRbxmx(elements: UIElement[]): string {
  const elMap = new Map(elements.map(e => [e.id, e]))
  let xml = '<?xml version="1.0" encoding="utf-8"?>\n<roblox version="4">\n'

  function emitXml(el: UIElement, indent = 1) {
    const pad = '  '.repeat(indent)
    xml += `${pad}<Item class="${el.type}">\n`
    xml += `${pad}  <Properties>\n`
    xml += `${pad}    <string name="Name">${escapeXml(el.name)}</string>\n`
    xml += `${pad}    <UDim2 name="Position">{${el.position.X}, 0},{${el.position.Y}, 0}</UDim2>\n`
    xml += `${pad}    <UDim2 name="Size">{${el.size.X}, 0},{${el.size.Y}, 0}</UDim2>\n`

    for (const [k, v] of Object.entries(el.properties)) {
      if (k === 'CornerRadius') {
        xml += `${pad}    <UDim name="CornerRadius">{0, ${v}}</UDim>\n`
      } else if (k === 'BackgroundColor3' || k === 'TextColor3' || k === 'BorderColor3') {
        const c = parseColor(v)
        const m = c.match(/rgb\((\d+),(\d+),(\d+)\)/)
        if (m) xml += `${pad}    <Color3 name="${k}">${+m[1]}, ${+m[2]}, ${+m[3]}</Color3>\n`
        else if (typeof v === 'string' && v.startsWith('#')) {
          const hex = v.slice(1)
          xml += `${pad}    <Color3 name="${k}">${parseInt(hex.slice(0,2),16)}, ${parseInt(hex.slice(2,4),16)}, ${parseInt(hex.slice(4,6),16)}</Color3>\n`
        }
      } else if (k === 'AnchorPoint' && typeof v === 'object') {
        xml += `${pad}    <Vector2 name="AnchorPoint">${v.X || 0}, ${v.Y || 0}</Vector2>\n`
      } else if (typeof v === 'string') {
        xml += `${pad}    <string name="${k}">${escapeXml(v)}</string>\n`
      } else if (typeof v === 'number') {
        xml += `${pad}    <float name="${k}">${v}</float>\n`
      } else if (typeof v === 'boolean') {
        xml += `${pad}    <bool name="${k}">${v}</bool>\n`
      }
    }
    xml += `${pad}  </Properties>\n`

    for (const cid of el.children) {
      const child = elMap.get(cid)
      if (child) emitXml(child, indent + 1)
    }
    xml += `${pad}</Item>\n`
  }

  const roots = elements.filter(e => !e.parentId)
  for (const root of roots) emitXml(root, 1)
  xml += '</roblox>'
  return xml
}

function escapeXml(s: string) { return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }

export default function UIGenerator() {
  const [elements, setElements] = useState<UIElement[]>([])
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [buildMode, setBuildMode] = useState(false)
  const [zoom, setZoom] = useState(1)
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [actionLog, setActionLog] = useState<ActionLogEntry[]>([])
  const [showExport, setShowExport] = useState(false)
  const [showImageSearch, setShowImageSearch] = useState(false)
  const [imageSearchQuery, setImageSearchQuery] = useState('')
  const [showAddMenu, setShowAddMenu] = useState(false)
  const [history, setHistory] = useState<UIElement[][]>([[]])
  const [historyIdx, setHistoryIdx] = useState(0)
  const [isDragging, setIsDragging] = useState(false)
  const [dragStart, setDragStart] = useState<{ x: number; y: number; elX: number; elY: number } | null>(null)
  const [isResizing, setIsResizing] = useState(false)
  const [resizeStart, setResizeStart] = useState<{ x: number; y: number; w: number; h: number } | null>(null)
  const [resizeCorner, setResizeCorner] = useState<string>('')
  const canvasRef = useRef<HTMLDivElement>(null)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const chatContainerRef = useRef<HTMLDivElement>(null)

  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages])

  const selectedEl = useMemo(() => elements.find(e => e.id === selectedId) || null, [elements, selectedId])

  const pushHistory = useCallback((newEls: UIElement[]) => {
    setHistory(prev => [...prev.slice(0, historyIdx + 1), newEls])
    setHistoryIdx(prev => prev + 1)
  }, [historyIdx])

  const undo = useCallback(() => {
    if (historyIdx > 0) { setHistoryIdx(historyIdx - 1); setElements(history[historyIdx - 1]); setSelectedId(null) }
  }, [historyIdx, history])

  const redo = useCallback(() => {
    if (historyIdx < history.length - 1) { setHistoryIdx(historyIdx + 1); setElements(history[historyIdx + 1]); setSelectedId(null) }
  }, [historyIdx, history])

  const addElement = useCallback((type: string, parentId?: string | null, props?: Partial<UIElement>) => {
    const id = genId()
    const name = `${type}_${elements.filter(e => e.type === type).length + 1}`
    const newEl: UIElement = {
      id, type, name,
      parentId: parentId ?? null,
      position: { X: 0.25 + Math.random() * 0.1, Y: 0.25 + Math.random() * 0.1 },
      size: { X: 0.3, Y: 0.2 },
      properties: {
        BackgroundColor3: type === 'TextLabel' || type === 'TextButton' ? '#2a2a3e' : '#1a1a2e',
        BackgroundTransparency: 0,
        BorderSizePixel: 0,
        TextColor3: '#ffffff',
        TextScaled: true,
        Font: 'GothamBold',
        Text: type.includes('Text') ? 'Text' : '',
        Image: '',
        AnchorPoint: { X: 0.5, Y: 0.5 },
        ZIndex: elements.length + 1,
        ...props,
      },
      children: [],
      zIndex: elements.length + 1,
    }
    if (type === 'UICorner') { newEl.properties.CornerRadius = 8; newEl.size = { X: 0, Y: 0 }; newEl.position = { X: 0, Y: 0 } }
    const newEls = [...elements, newEl]
    if (parentId) {
      const parent = newEls.find(e => e.id === parentId)
      if (parent) parent.children = [...parent.children, id]
    }
    setElements(newEls)
    pushHistory(newEls)
    return id
  }, [elements, pushHistory])

  const modifyElement = useCallback((targetId: string, props: Record<string, any>) => {
    const newEls = elements.map(e => {
      if (e.id === targetId) return { ...e, properties: { ...e.properties, ...props } }
      return e
    })
    setElements(newEls)
    pushHistory(newEls)
  }, [elements, pushHistory])

  const removeElement = useCallback((targetId: string) => {
    const newEls = elements.filter(e => e.id !== targetId).map(e => ({
      ...e, children: e.children.filter(c => c !== targetId)
    }))
    setElements(newEls)
    pushHistory(newEls)
    if (selectedId === targetId) setSelectedId(null)
  }, [elements, selectedId, pushHistory])

  const addLog = useCallback((type: ActionLogEntry['type'], message: string) => {
    setActionLog(prev => [...prev.slice(-50), { type, message, time: Date.now() }])
  }, [])

  const applyCommands = useCallback((commands: any[]) => {
    const newEls = [...elements]
    for (const cmd of commands) {
      if (cmd.action === 'add') {
        const id = genId()
        const el: UIElement = {
          id, type: cmd.elementType || 'Frame', name: cmd.name || `${cmd.elementType}_${newEls.length + 1}`,
          parentId: cmd.parent ? newEls.find(e => e.name === cmd.parent)?.id || null : null,
          position: cmd.position || { X: 0.25, Y: 0.25 },
          size: cmd.size || { X: 0.3, Y: 0.2 },
          properties: { AnchorPoint: { X: 0.5, Y: 0.5 }, BackgroundTransparency: 0, BorderSizePixel: 0, TextScaled: true, Font: 'GothamBold', Text: '', Image: '', ZIndex: newEls.length + 1, ...cmd.properties },
          children: [], zIndex: newEls.length + 1,
        }
        newEls.push(el)
        if (el.parentId) { const p = newEls.find(e => e.id === el.parentId); if (p) p.children = [...p.children, id] }
        addLog('add', `Added ${el.type} "${el.name}"`)
      } else if (cmd.action === 'modify') {
        const target = newEls.find(e => e.name === cmd.target || e.id === cmd.target)
        if (target) { Object.assign(target.properties, cmd.properties); addLog('modify', `Modified "${target.name}"`) }
      } else if (cmd.action === 'remove') {
        const target = newEls.find(e => e.name === cmd.target || e.id === cmd.target)
        if (target) {
          newEls.splice(newEls.indexOf(target), 1)
          newEls.forEach(e => { e.children = e.children.filter(c => c !== target.id) })
          addLog('remove', `Removed "${target.name}"`)
        }
      }
    }
    setElements(newEls)
    pushHistory(newEls)
  }, [elements, pushHistory, addLog])

  const sendMessage = async (text?: string) => {
    const msg = (text || input).trim()
    if (!msg || isLoading) return
    const userMsg: ChatMessage = { role: 'user', content: msg }
    setMessages(p => [...p, userMsg])
    setInput(''); setIsLoading(true)
    try {
      const canvasState = elements.map(e => ({ name: e.name, type: e.type, position: e.position, size: e.size, properties: e.properties }))
      const resp = await fetch(CHAT_API, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: [...messages, userMsg].map(m => ({ role: m.role, content: m.content })), canvas_state: canvasState }),
      })
      const data = await resp.json()
      const assistantMsg: ChatMessage = { role: 'assistant', content: data.message || data.content || 'Done', commands: data.commands || [] }
      setMessages(p => [...p, assistantMsg])
      if (data.commands && data.commands.length > 0) applyCommands(data.commands)
      if (data.ask) addLog('info', 'AI has a question for you')
    } catch {
      setMessages(p => [...p, { role: 'assistant', content: 'Error connecting to AI. Please try again.' }])
      addLog('error', 'AI connection failed')
    }
    setIsLoading(false)
  }

  const handleCanvasMouseDown = useCallback((e: React.MouseEvent, elId: string) => {
    if (!buildMode) return
    e.stopPropagation()
    setSelectedId(elId)
    const el = elements.find(x => x.id === elId)
    if (!el) return
    const rect = canvasRef.current?.getBoundingClientRect()
    if (!rect) return
    setIsDragging(true)
    setDragStart({ x: e.clientX, y: e.clientY, elX: el.position.X, elY: el.position.Y })
  }, [buildMode, elements])

  const handleCanvasMouseMove = useCallback((e: React.MouseEvent) => {
    if (!isDragging || !dragStart || !selectedId) return
    const rect = canvasRef.current?.getBoundingClientRect()
    if (!rect) return
    const scaleX = CANVAS_W / (rect.width * zoom)
    const scaleY = CANVAS_H / (rect.height * zoom)
    const dx = (e.clientX - dragStart.x) * scaleX / CANVAS_W
    const dy = (e.clientY - dragStart.y) * scaleY / CANVAS_H
    const newX = Math.max(0, Math.min(1, dragStart.elX + dx))
    const newY = Math.max(0, Math.min(1, dragStart.elY + dy))
    const newEls = elements.map(el => el.id === selectedId ? { ...el, position: { X: newX, Y: newY } } : el)
    setElements(newEls)
  }, [isDragging, dragStart, selectedId, elements, zoom])

  const handleCanvasMouseUp = useCallback(() => {
    if (isDragging) { setIsDragging(false); setDragStart(null); pushHistory(elements) }
    if (isResizing) { setIsResizing(false); setResizeStart(null); pushHistory(elements) }
  }, [isDragging, isResizing, elements, pushHistory])

  const handleResizeStart = useCallback((e: React.MouseEvent, corner: string) => {
    e.stopPropagation()
    if (!selectedEl) return
    setIsResizing(true)
    setResizeCorner(corner)
    setResizeStart({ x: e.clientX, y: e.clientY, w: selectedEl.size.X, h: selectedEl.size.Y })
  }, [selectedEl])

  const handleResizeMove = useCallback((e: React.MouseEvent) => {
    if (!isResizing || !resizeStart || !selectedId) return
    const rect = canvasRef.current?.getBoundingClientRect()
    if (!rect) return
    const scaleX = CANVAS_W / (rect.width * zoom)
    const dx = (e.clientX - resizeStart.x) * scaleX / CANVAS_W
    const dy = (e.clientY - resizeStart.y) * (CANVAS_H / (rect.height * zoom)) / CANVAS_H
    let newW = resizeStart.w
    let newH = resizeStart.h
    if (resizeCorner.includes('e')) newW = Math.max(0.02, resizeStart.w + dx)
    if (resizeCorner.includes('w')) newW = Math.max(0.02, resizeStart.w - dx)
    if (resizeCorner.includes('s')) newH = Math.max(0.02, resizeStart.h + dy)
    if (resizeCorner.includes('n')) newH = Math.max(0.02, resizeStart.h - dy)
    const newEls = elements.map(el => el.id === selectedId ? { ...el, size: { X: newW, Y: newH } } : el)
    setElements(newEls)
  }, [isResizing, resizeStart, selectedId, elements, zoom, resizeCorner])

  const addImageFromUrl = useCallback((url: string) => {
    const id = addElement('ImageLabel', null, { Image: url, BackgroundTransparency: 1 })
    addLog('info', `Added image from URL`)
    setShowImageSearch(false)
  }, [addElement, addLog])

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url; a.download = filename; a.click()
    URL.revokeObjectURL(url)
  }

  const suggestedPrompts = [
    'A dark inventory frame with rounded corners',
    'A health bar with gradient fill',
    'A shop GUI with item slots',
    'A main menu with play and settings buttons',
    'A minimap in the corner',
    'A chat box at the bottom',
  ]

  const getElementStyle = (el: UIElement): React.CSSProperties => {
    const p = el.properties
    const radius = p.CornerRadius || 0
    const bgColor = el.type === 'ImageLabel' || el.type === 'ImageButton' ? 'transparent' : parseColor(p.BackgroundColor3)
    const bgTrans = p.BackgroundTransparency || 0
    return {
      position: 'absolute',
      left: `${el.position.X * 100}%`,
      top: `${el.position.Y * 100}%`,
      width: `${el.size.X * 100}%`,
      height: `${el.size.Y * 100}%`,
      transform: `translate(-50%, -50%)${p.Rotation ? ` rotate(${p.Rotation}deg)` : ''}`,
      backgroundColor: bgTrans >= 1 ? 'transparent' : bgColor,
      borderRadius: radius,
      border: p.BorderSizePixel ? `${p.BorderSizePixel}px solid ${parseColor(p.BorderColor3 || '#000000')}` : undefined,
      zIndex: el.zIndex || 1,
      overflow: el.type === 'ScrollingFrame' ? 'auto' : 'hidden',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      boxShadow: p.Shadow ? `0 4px 12px rgba(0,0,0,0.3)` : undefined,
    }
  }

  return (
    <div className="flex flex-col lg:flex-row rounded-2xl bg-bg-secondary border border-border-primary overflow-hidden" style={{ height: '70vh', minHeight: 600 }}>
      {/* Left: Canvas */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Canvas Toolbar */}
        <div className="flex items-center gap-2 px-3 py-2 border-b border-border-primary bg-bg-elevated/50">
          <div className="flex items-center gap-1">
            <button onClick={() => setBuildMode(!buildMode)} className={cn('flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium transition-all', buildMode ? 'bg-accent-blue/15 text-accent-blue border border-accent-blue/25' : 'text-text-muted hover:text-text-primary border border-transparent hover:border-border-hover')}>
              <Grid3X3 size={12} /> Build
            </button>
            <button onClick={() => setShowImageSearch(true)} className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs text-text-muted hover:text-text-primary border border-transparent hover:border-border-hover transition-all">
              <ImageIcon size={12} /> Image
            </button>
          </div>
          <div className="h-4 w-px bg-border-primary" />
          <div className="flex items-center gap-1">
            <button onClick={undo} disabled={historyIdx <= 0} className="p-1.5 rounded-lg text-text-muted hover:text-text-primary disabled:opacity-30 transition-all"><RotateCcw size={12} /></button>
            <button onClick={redo} disabled={historyIdx >= history.length - 1} className="p-1.5 rounded-lg text-text-muted hover:text-text-primary disabled:opacity-30 transition-all rotate-180"><RotateCcw size={12} /></button>
          </div>
          <div className="h-4 w-px bg-border-primary" />
          <div className="flex items-center gap-1">
            <button onClick={() => setZoom(z => Math.min(2, z + 0.1))} className="p-1.5 rounded-lg text-text-muted hover:text-text-primary transition-all"><ZoomIn size={12} /></button>
            <span className="text-[10px] text-text-dim w-8 text-center">{Math.round(zoom * 100)}%</span>
            <button onClick={() => setZoom(z => Math.max(0.3, z - 0.1))} className="p-1.5 rounded-lg text-text-muted hover:text-text-primary transition-all"><ZoomOut size={12} /></button>
          </div>
          <div className="flex-1" />
          <div className="flex items-center gap-1">
            <div className="relative">
              <button onClick={() => setShowAddMenu(!showAddMenu)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-accent-blue/15 text-accent-blue border border-accent-blue/25 hover:bg-accent-blue/25 transition-all">
                <Plus size={12} /> Add Element
              </button>
              {showAddMenu && (
                <div className="absolute top-full mt-1 right-0 z-50 bg-bg-elevated border border-border-primary rounded-xl shadow-2xl p-1 min-w-[160px]">
                  {ELEMENT_TYPES.map(et => (
                    <button key={et.type} onClick={() => { addElement(et.type, selectedId); setShowAddMenu(false) }}
                      className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-xs text-text-primary hover:bg-bg-secondary transition-all text-left">
                      <span className="w-6 text-center opacity-50">{et.icon}</span>
                      <span>{et.desc}</span>
                    </button>
                  ))}
                </div>
              )}
            </div>
            <button onClick={() => setShowExport(true)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-accent-purple/15 text-accent-purple border border-accent-purple/25 hover:bg-accent-purple/25 transition-all">
              <Download size={12} /> Export
            </button>
          </div>
        </div>

        {/* Canvas Area */}
        <div className="flex-1 overflow-auto bg-[#0a0a0f] flex items-center justify-center p-6" onClick={() => { setSelectedId(null); setShowAddMenu(false) }}>
          <div ref={canvasRef} className="relative" style={{ width: CANVAS_W * 0.55 * zoom, height: CANVAS_H * 0.55 * zoom, transition: 'width 0.2s, height 0.2s' }}
            onMouseMove={(e) => { handleCanvasMouseMove(e); handleResizeMove(e) }} onMouseUp={handleCanvasMouseUp} onMouseLeave={handleCanvasMouseUp}>
            {buildMode && (
              <div className="absolute inset-0 pointer-events-none" style={{
                backgroundImage: 'linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)',
                backgroundSize: `${CANVAS_W * 0.55 * zoom / 20}px ${CANVAS_H * 0.55 * zoom / 20}px`
              }} />
            )}
            {/* Screen border */}
            <div className="absolute inset-0 border border-white/5 rounded-lg pointer-events-none" />
            {/* Elements */}
            {elements.filter(e => !e.parentId || !elements.find(p => p.id === e.parentId)).map(el => (
              <div key={el.id} style={getElementStyle(el)}
                className={cn('cursor-pointer transition-shadow group', selectedId === el.id && 'ring-2 ring-accent-blue ring-offset-1 ring-offset-transparent')}
                onMouseDown={(e) => handleCanvasMouseDown(e, el.id)} onClick={(e) => { e.stopPropagation(); setSelectedId(el.id) }}>
                {el.type === 'TextLabel' && <span style={{ color: parseColor(el.properties.TextColor3), fontSize: el.properties.TextScaled ? '100%' : 14, fontFamily: el.properties.Font === 'GothamBold' ? 'inherit' : undefined }} className="px-1 text-center font-bold truncate w-full">{el.properties.Text || 'Text'}</span>}
                {el.type === 'TextButton' && <span style={{ color: parseColor(el.properties.TextColor3), fontSize: el.properties.TextScaled ? '100%' : 14 }} className="px-1 text-center font-bold truncate w-full">{el.properties.Text || 'Button'}</span>}
                {el.type === 'ImageLabel' && el.properties.Image && <img src={el.properties.Image} alt="" className="w-full h-full object-cover" style={{ opacity: 1 - (el.properties.ImageTransparency || 0) }} />}
                {el.type === 'ScrollingFrame' && <div className="w-full h-full overflow-auto p-1" />}
                {/* Resize handles */}
                {selectedId === el.id && buildMode && (
                  <>
                    {['nw', 'ne', 'sw', 'se'].map(corner => (
                      <div key={corner} className={cn('absolute w-2.5 h-2.5 bg-accent-blue rounded-full border border-white shadow-md z-50',
                        corner === 'nw' && '-top-1.5 -left-1.5 cursor-nw-resize',
                        corner === 'ne' && '-top-1.5 -right-1.5 cursor-ne-resize',
                        corner === 'sw' && '-bottom-1.5 -left-1.5 cursor-sw-resize',
                        corner === 'se' && '-bottom-1.5 -right-1.5 cursor-se-resize'
                      )} onMouseDown={(e) => handleResizeStart(e, corner)} />
                    ))}
                    <div className="absolute -top-5 left-1/2 -translate-x-1/2 px-1.5 py-0.5 rounded bg-accent-blue text-[9px] text-white font-mono whitespace-nowrap">{el.name}</div>
                  </>
                )}
                {/* Render children */}
                {el.children.map(cid => {
                  const child = elements.find(e => e.id === cid)
                  if (!child) return null
                  const cp = child.position
                  const cs = child.size
                  return (
                    <div key={cid} style={{ position: 'absolute', left: `${cp.X * 100}%`, top: `${cp.Y * 100}%`, width: `${cs.X * 100}%`, height: `${cs.Y * 100}%`, transform: 'translate(-50%, -50%)', borderRadius: child.properties.CornerRadius || 0, backgroundColor: child.properties.BackgroundTransparency >= 1 ? 'transparent' : parseColor(child.properties.BackgroundColor3), zIndex: child.zIndex || 1, display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', border: child.properties.BorderSizePixel ? `${child.properties.BorderSizePixel}px solid ${parseColor(child.properties.BorderColor3 || '#000')}` : undefined }}
                      className={cn('cursor-pointer', selectedId === cid && 'ring-2 ring-accent-blue')}
                      onClick={(e) => { e.stopPropagation(); setSelectedId(cid) }}
                      onMouseDown={(e) => handleCanvasMouseDown(e, cid)}>
                      {child.type === 'TextLabel' && <span style={{ color: parseColor(child.properties.TextColor3), fontSize: child.properties.TextScaled ? '100%' : 14 }} className="px-1 text-center font-bold truncate w-full">{child.properties.Text || 'Text'}</span>}
                      {child.type === 'TextButton' && <span style={{ color: parseColor(child.properties.TextColor3), fontSize: child.properties.TextScaled ? '100%' : 14 }} className="px-1 text-center font-bold truncate w-full">{child.properties.Text || 'Button'}</span>}
                      {child.type === 'ImageLabel' && child.properties.Image && <img src={child.properties.Image} alt="" className="w-full h-full object-cover" style={{ opacity: 1 - (child.properties.ImageTransparency || 0) }} />}
                    </div>
                  )
                })}
              </div>
            ))}
            {elements.length === 0 && (
              <div className="absolute inset-0 flex flex-col items-center justify-center text-white/20 pointer-events-none">
                <Box size={40} className="mb-3 opacity-30" />
                <p className="text-sm font-medium">Empty Canvas</p>
                <p className="text-xs opacity-60">Use AI or add elements manually</p>
              </div>
            )}
          </div>
        </div>

        {/* Element Info Bar */}
        {selectedEl && (
          <div className="flex items-center gap-3 px-3 py-2 border-t border-border-primary bg-bg-elevated/50 text-xs">
            <span className="text-accent-blue font-mono">{selectedEl.type}</span>
            <span className="text-text-muted">{selectedEl.name}</span>
            <span className="text-text-dim">Pos: ({(selectedEl.position.X * 100).toFixed(1)}%, {(selectedEl.position.Y * 100).toFixed(1)}%)</span>
            <span className="text-text-dim">Size: ({(selectedEl.size.X * 100).toFixed(1)}%, {(selectedEl.size.Y * 100).toFixed(1)}%)</span>
            <div className="flex-1" />
            <button onClick={() => { modifyElement(selectedEl.id, {}); const p = selectedEl.properties; addLog('info', `Duplicated "${selectedEl.name}"`) }}
              className="px-2 py-1 rounded text-[10px] text-text-muted hover:text-text-primary hover:bg-bg-secondary transition-all">Duplicate</button>
            <button onClick={() => removeElement(selectedEl.id)} className="px-2 py-1 rounded text-[10px] text-red-400 hover:bg-red-500/10 transition-all">Delete</button>
          </div>
        )}
      </div>

      {/* Right: AI Chat + Activity Log */}
      <div className="w-full lg:w-[380px] border-l border-border-primary flex flex-col bg-bg-primary/50">
        {/* Tabs */}
        <div className="flex border-b border-border-primary">
          <button className="flex-1 px-4 py-2.5 text-xs font-medium text-accent-purple border-b-2 border-accent-purple bg-accent-purple/5">AI Assistant</button>
          <button onClick={() => {}} className="flex-1 px-4 py-2.5 text-xs font-medium text-text-muted hover:text-text-primary transition-all">Activity ({actionLog.length})</button>
        </div>

        {/* Chat */}
        <div ref={chatContainerRef} className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
          {messages.length === 0 && (
            <div className="flex flex-col items-center justify-center h-full text-center px-4">
              <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-accent-purple/20 to-accent-pink/20 border border-accent-purple/10 flex items-center justify-center mb-4">
                <Sparkles size={24} className="text-accent-purple/60" />
              </div>
              <h3 className="text-sm font-bold text-text-primary mb-1">Build your UI with AI</h3>
              <p className="text-xs text-text-muted mb-4 leading-relaxed">Describe what you want and AI will add elements to the canvas in real-time.</p>
              <div className="flex flex-wrap gap-1.5 justify-center">
                {suggestedPrompts.map((p, i) => (
                  <button key={i} onClick={() => sendMessage(p)}
                    className="px-3 py-1.5 rounded-lg text-[10px] text-text-secondary bg-bg-elevated border border-border-primary hover:border-accent-purple/30 hover:text-accent-purple transition-all">
                    {p}
                  </button>
                ))}
              </div>
            </div>
          )}

          {messages.map((msg, i) => (
            <div key={i} className={cn('flex', msg.role === 'user' ? 'justify-end' : 'justify-start')}>
              <div className={cn('max-w-[90%] px-3 py-2 rounded-xl text-xs leading-relaxed',
                msg.role === 'user' ? 'bg-accent-blue text-white rounded-br-md' : 'bg-bg-elevated text-text-primary rounded-bl-md border border-border-primary')}>
                <p className="whitespace-pre-wrap break-words">{msg.content}</p>
                {msg.commands && msg.commands.length > 0 && (
                  <div className="mt-1.5 flex flex-wrap gap-1">
                    {msg.commands.map((c: any, j: number) => (
                      <span key={j} className={cn('px-1.5 py-0.5 rounded text-[9px] font-mono',
                        c.action === 'add' && 'bg-green-500/10 text-green-400',
                        c.action === 'modify' && 'bg-yellow-500/10 text-yellow-400',
                        c.action === 'remove' && 'bg-red-500/10 text-red-400')}>
                        {c.action}: {c.name || c.target || c.elementType}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ))}
          {isLoading && (
            <div className="flex justify-start">
              <div className="bg-bg-elevated border border-border-primary rounded-xl rounded-bl-md px-3 py-2">
                <div className="flex gap-1">
                  <span className="w-1 h-1 rounded-full bg-accent-purple animate-bounce" style={{ animationDelay: '0ms' }} />
                  <span className="w-1 h-1 rounded-full bg-accent-purple animate-bounce" style={{ animationDelay: '150ms' }} />
                  <span className="w-1 h-1 rounded-full bg-accent-purple animate-bounce" style={{ animationDelay: '300ms' }} />
                </div>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div className="px-3 pb-3 pt-1 border-t border-border-primary">
          <div className="flex items-end gap-2 bg-bg-elevated rounded-xl px-3 py-2 border border-border-primary focus-within:border-accent-purple/50 transition-colors">
            <textarea value={input} onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage() } }}
              placeholder="Describe your UI..." rows={1}
              className="flex-1 bg-transparent text-text-primary text-xs resize-none focus:outline-none placeholder:text-text-dim max-h-20" />
            <button onClick={() => sendMessage()} disabled={!input.trim() || isLoading}
              className={cn('h-7 w-7 rounded-lg flex-shrink-0 flex items-center justify-center transition-all',
                input.trim() && !isLoading ? 'bg-accent-purple text-white hover:bg-purple-600' : 'bg-bg-tertiary text-text-dim')}>
              {isLoading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Send className="h-3 w-3" />}
            </button>
          </div>
        </div>
      </div>

      {/* Image Search Modal */}
      {showImageSearch && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={() => setShowImageSearch(false)}>
          <div className="bg-bg-elevated border border-border-primary rounded-2xl shadow-2xl w-[500px] max-h-[80vh] flex flex-col" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b border-border-primary">
              <h3 className="text-sm font-bold text-text-primary">Add Image</h3>
              <button onClick={() => setShowImageSearch(false)} className="p-1 rounded-lg hover:bg-bg-secondary transition-all"><X size={14} className="text-text-muted" /></button>
            </div>
            <div className="p-4 space-y-3">
              <div>
                <label className="text-xs text-text-muted mb-1 block">Image URL</label>
                <input value={imageSearchQuery} onChange={(e) => setImageSearchQuery(e.target.value)} placeholder="Paste image URL or search term..."
                  className="w-full px-3 py-2 rounded-xl bg-bg-secondary border border-border-primary text-xs text-text-primary placeholder:text-text-dim focus:outline-none focus:border-accent-purple/50" />
              </div>
              <div className="flex gap-2">
                <button onClick={() => { if (imageSearchQuery) addImageFromUrl(imageSearchQuery) }}
                  className="flex-1 px-4 py-2 rounded-xl bg-accent-purple text-white text-xs font-medium hover:bg-purple-600 transition-all">Add Image</button>
                <label className="px-4 py-2 rounded-xl bg-bg-secondary border border-border-primary text-xs text-text-muted hover:text-text-primary cursor-pointer transition-all">
                  <Upload size={12} className="inline mr-1.5" />Upload
                  <input type="file" accept="image/*" className="hidden" onChange={(e) => {
                    const file = e.target.files?.[0]; if (file) { const url = URL.createObjectURL(file); addImageFromUrl(url) }
                  }} />
                </label>
              </div>
              <div className="border-t border-border-primary pt-3">
                <p className="text-[10px] text-text-dim mb-2">Quick search:</p>
                <div className="flex flex-wrap gap-1.5">
                  {['robot icon', 'sword icon', 'coin icon', 'heart icon', 'star icon', 'shield icon', 'gem icon', 'crown icon'].map(q => (
                    <button key={q} onClick={() => setImageSearchQuery(q)} className="px-2 py-1 rounded-lg text-[10px] text-text-muted bg-bg-secondary border border-border-primary hover:border-accent-purple/30 transition-all">{q}</button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Export Modal */}
      {showExport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={() => setShowExport(false)}>
          <div className="bg-bg-elevated border border-border-primary rounded-2xl shadow-2xl w-[480px] flex flex-col" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b border-border-primary">
              <h3 className="text-sm font-bold text-text-primary">Export UI</h3>
              <button onClick={() => setShowExport(false)} className="p-1 rounded-lg hover:bg-bg-secondary transition-all"><X size={14} className="text-text-muted" /></button>
            </div>
            <div className="p-4 space-y-3">
              <p className="text-xs text-text-muted">{elements.length} elements on canvas</p>
              <button onClick={() => { downloadFile(generateLua(elements), 'GeneratedUI.lua', 'text/plain'); setShowExport(false) }}
                className="w-full flex items-center gap-3 p-4 rounded-xl bg-bg-secondary border border-border-primary hover:border-accent-green/30 transition-all text-left group">
                <div className="w-10 h-10 rounded-xl bg-accent-green/10 flex items-center justify-center"><FileCode2 size={18} className="text-accent-green" /></div>
                <div>
                  <p className="text-sm font-semibold text-text-primary group-hover:text-accent-green transition-colors">Lua Script</p>
                  <p className="text-[10px] text-text-muted">Paste into Roblox Studio Command Bar or LocalScript</p>
                </div>
              </button>
              <button onClick={() => { downloadFile(generateRbxmx(elements), 'GeneratedUI.rbxmx', 'application/xml'); setShowExport(false) }}
                className="w-full flex items-center gap-3 p-4 rounded-xl bg-bg-secondary border border-border-primary hover:border-accent-blue/30 transition-all text-left group">
                <div className="w-10 h-10 rounded-xl bg-accent-blue/10 flex items-center justify-center"><FileJson size={18} className="text-accent-blue" /></div>
                <div>
                  <p className="text-sm font-semibold text-text-primary group-hover:text-accent-blue transition-colors">RBXMX Model</p>
                  <p className="text-[10px] text-text-muted">Import via Roblox Studio → Insert from File</p>
                </div>
              </button>
              <button onClick={() => { navigator.clipboard.writeText(generateLua(elements)); setShowExport(false) }}
                className="w-full flex items-center gap-3 p-4 rounded-xl bg-bg-secondary border border-border-primary hover:border-accent-purple/30 transition-all text-left group">
                <div className="w-10 h-10 rounded-xl bg-accent-purple/10 flex items-center justify-center"><Copy size={18} className="text-accent-purple" /></div>
                <div>
                  <p className="text-sm font-semibold text-text-primary group-hover:text-accent-purple transition-colors">Copy to Clipboard</p>
                  <p className="text-[10px] text-text-muted">Copy Lua script to clipboard</p>
                </div>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function Copy(props: any) {
  return <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2" /><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" /></svg>
}
